export interface IllustrationAsset {
  id: string;
  name: string;
  fileName: string;
  src: string;
  alt: string;
  usage: string;
  width: number;
  height: number;
}

const ILLUSTRATION_BASE_PATH = '/assets/illustrations/a-illustration';

export const ILLUSTRATION_ASSETS: IllustrationAsset[] = [
  {
    id: '404',
    name: '404',
    fileName: '404.png',
    src: `${ILLUSTRATION_BASE_PATH}/404.png`,
    alt: '404 illustration',
    usage: 'Use for not-found or missing-page states.',
    width: 796,
    height: 784,
  },
  {
    id: 'clock',
    name: 'Clock',
    fileName: 'clock.png',
    src: `${ILLUSTRATION_BASE_PATH}/clock.png`,
    alt: 'Clock illustration',
    usage: 'Use for waiting, scheduled, or time-related empty states.',
    width: 784,
    height: 784,
  },
  {
    id: 'confirm',
    name: 'Confirm',
    fileName: 'confirm.png',
    src: `${ILLUSTRATION_BASE_PATH}/confirm.png`,
    alt: 'Confirm illustration',
    usage: 'Use for confirmation dialogs or review-before-submit states.',
    width: 784,
    height: 784,
  },
  {
    id: 'delete',
    name: 'Delete',
    fileName: 'delete.png',
    src: `${ILLUSTRATION_BASE_PATH}/delete.png`,
    alt: 'Delete illustration',
    usage: 'Use for delete confirmation or destructive action states.',
    width: 784,
    height: 784,
  },
  {
    id: 'empty',
    name: 'Empty',
    fileName: 'empty.png',
    src: `${ILLUSTRATION_BASE_PATH}/empty.png`,
    alt: 'Empty illustration',
    usage: 'Use when a list, table, or panel has no content.',
    width: 784,
    height: 784,
  },
  {
    id: 'error',
    name: 'Error',
    fileName: 'error.png',
    src: `${ILLUSTRATION_BASE_PATH}/error.png`,
    alt: 'Error illustration',
    usage: 'Use for failed operations or blocking error states.',
    width: 784,
    height: 784,
  },
  {
    id: 'feedback',
    name: 'Feedback',
    fileName: 'feedback.png',
    src: `${ILLUSTRATION_BASE_PATH}/feedback.png`,
    alt: 'Feedback illustration',
    usage: 'Use for feedback, survey, or user response states.',
    width: 784,
    height: 784,
  },
  {
    id: 'file-word',
    name: 'Word File',
    fileName: 'file-word.png',
    src: `${ILLUSTRATION_BASE_PATH}/file-word.png`,
    alt: 'Word file illustration',
    usage: 'Use for Microsoft Word documents or DOC/DOCX file previews.',
    width: 128,
    height: 128,
  },
  {
    id: 'file-pdf',
    name: 'PDF File',
    fileName: 'file-pdf.png',
    src: `${ILLUSTRATION_BASE_PATH}/file-pdf.png`,
    alt: 'PDF file illustration',
    usage: 'Use for PDF documents or PDF file previews.',
    width: 128,
    height: 128,
  },
  {
    id: 'file-xml',
    name: 'XML File',
    fileName: 'file-xml.png',
    src: `${ILLUSTRATION_BASE_PATH}/file-xml.png`,
    alt: 'XML file illustration',
    usage: 'Use for XML files, data export files, or structured document previews.',
    width: 128,
    height: 128,
  },
  {
    id: 'file-image',
    name: 'Image File',
    fileName: 'file-image.png',
    src: `${ILLUSTRATION_BASE_PATH}/file-image.png`,
    alt: 'Image file illustration',
    usage: 'Use for image uploads, image file previews, or media attachments.',
    width: 128,
    height: 128,
  },
  {
    id: 'file-excel',
    name: 'Excel File',
    fileName: 'file-excel.png',
    src: `${ILLUSTRATION_BASE_PATH}/file-excel.png`,
    alt: 'Excel file illustration',
    usage: 'Use for Microsoft Excel documents or XLS/XLSX file previews.',
    width: 128,
    height: 128,
  },
  {
    id: 'file-error',
    name: 'Error File',
    fileName: 'file-error.png',
    src: `${ILLUSTRATION_BASE_PATH}/file-error.png`,
    alt: 'Error file illustration',
    usage: 'Use for unsupported files, failed file previews, or file validation errors.',
    width: 128,
    height: 128,
  },
  {
    id: 'notification',
    name: 'Notification',
    fileName: 'notification.png',
    src: `${ILLUSTRATION_BASE_PATH}/notification.png`,
    alt: 'Notification illustration',
    usage: 'Use for notifications, alerts, or message center states.',
    width: 784,
    height: 784,
  },
  {
    id: 'search',
    name: 'Search',
    fileName: 'search.png',
    src: `${ILLUSTRATION_BASE_PATH}/search.png`,
    alt: 'Search illustration',
    usage: 'Use for search empty states or no-result screens.',
    width: 784,
    height: 784,
  },
  {
    id: 'success',
    name: 'Success',
    fileName: 'success.png',
    src: `${ILLUSTRATION_BASE_PATH}/success.png`,
    alt: 'Success illustration',
    usage: 'Use after successful submission, completion, or saved states.',
    width: 784,
    height: 784,
  },
  {
    id: 'unable-to-load-data',
    name: 'Unable To Load Data',
    fileName: 'unable-to-load-data.png',
    src: `${ILLUSTRATION_BASE_PATH}/unable-to-load-data.png`,
    alt: 'Unable to load data illustration',
    usage: 'Use when API data cannot be loaded or refreshed.',
    width: 795,
    height: 784,
  },
  {
    id: 'upload',
    name: 'Upload',
    fileName: 'upload.png',
    src: `${ILLUSTRATION_BASE_PATH}/upload.png`,
    alt: 'Upload illustration',
    usage: 'Use for upload entry points, upload empty states, or file import screens.',
    width: 784,
    height: 784,
  },
  {
    id: 'warning',
    name: 'Warning',
    fileName: 'warning.png',
    src: `${ILLUSTRATION_BASE_PATH}/warning.png`,
    alt: 'Warning illustration',
    usage: 'Use for caution, warning, or recoverable risk states.',
    width: 784,
    height: 784,
  },
];
