export interface IllustrationAsset {
  id: string;
  name: string;
  fileName: string;
  src: string;
  alt: string;
  usage: string;
  width: number;
  height: number;
}

const ILLUSTRATION_BASE_PATH = '/assets/illustrations/a-illustration';

export const ILLUSTRATION_ASSETS: IllustrationAsset[] = [
  {
    id: '404',
    name: '404',
    fileName: '404.png',
    src: `${ILLUSTRATION_BASE_PATH}/404.png`,
    alt: '404 illustration',
    usage: 'Use for not-found or missing-page states.',
    width: 796,
    height: 784,
  },
  {
    id: 'clock',
    name: 'Clock',
    fileName: 'clock.png',
    src: `${ILLUSTRATION_BASE_PATH}/clock.png`,
    alt: 'Clock illustration',
    usage: 'Use for waiting, scheduled, or time-related empty states.',
    width: 784,
    height: 784,
  },
  {
    id: 'confirm',
    name: 'Confirm',
    fileName: 'confirm.png',
    src: `${ILLUSTRATION_BASE_PATH}/confirm.png`,
    alt: 'Confirm illustration',
    usage: 'Use for confirmation dialogs or review-before-submit states.',
    width: 784,
    height: 784,
  },
  {
    id: 'delete',
    name: 'Delete',
    fileName: 'delete.png',
    src: `${ILLUSTRATION_BASE_PATH}/delete.png`,
    alt: 'Delete illustration',
    usage: 'Use for delete confirmation or destructive action states.',
    width: 784,
    height: 784,
  },
  {
    id: 'empty',
    name: 'Empty',
    fileName: 'empty.png',
    src: `${ILLUSTRATION_BASE_PATH}/empty.png`,
    alt: 'Empty illustration',
    usage: 'Use when a list, table, or panel has no content.',
    width: 784,
    height: 784,
  },
  {
    id: 'error',
    name: 'Error',
    fileName: 'error.png',
    src: `${ILLUSTRATION_BASE_PATH}/error.png`,
    alt: 'Error illustration',
    usage: 'Use for failed operations or blocking error states.',
    width: 784,
    height: 784,
  },
  {
    id: 'feedback',
    name: 'Feedback',
    fileName: 'feedback.png',
    src: `${ILLUSTRATION_BASE_PATH}/feedback.png`,
    alt: 'Feedback illustration',
    usage: 'Use for feedback, survey, or user response states.',
    width: 784,
    height: 784,
  },
  {
    id: 'file-word',
    name: 'Word File',
    fileName: 'file-word.png',
    src: `${ILLUSTRATION_BASE_PATH}/file-word.png`,
    alt: 'Word file illustration',
    usage: 'Use for Microsoft Word documents or DOC/DOCX file previews.',
    width: 128,
    height: 128,
  },
  {
    id: 'file-pdf',
    name: 'PDF File',
    fileName: 'file-pdf.png',
    src: `${ILLUSTRATION_BASE_PATH}/file-pdf.png`,
    alt: 'PDF file illustration',
    usage: 'Use for PDF documents or PDF file previews.',
    width: 128,
    height: 128,
  },
  {
    id: 'file-xml',
    name: 'XML File',
    fileName: 'file-xml.png',
    src: `${ILLUSTRATION_BASE_PATH}/file-xml.png`,
    alt: 'XML file illustration',
    usage: 'Use for XML files, data export files, or structured document previews.',
    width: 128,
    height: 128,
  },
  {
    id: 'file-image',
    name: 'Image File',
    fileName: 'file-image.png',
    src: `${ILLUSTRATION_BASE_PATH}/file-image.png`,
    alt: 'Image file illustration',
    usage: 'Use for image uploads, image file previews, or media attachments.',
    width: 128,
    height: 128,
  },
  {
    id: 'file-excel',
    name: 'Excel File',
    fileName: 'file-excel.png',
    src: `${ILLUSTRATION_BASE_PATH}/file-excel.png`,
    alt: 'Excel file illustration',
    usage: 'Use for Microsoft Excel documents or XLS/XLSX file previews.',
    width: 128,
    height: 128,
  },
  {
    id: 'file-error',
    name: 'Error File',
    fileName: 'file-error.png',
    src: `${ILLUSTRATION_BASE_PATH}/file-error.png`,
    alt: 'Error file illustration',
    usage: 'Use for unsupported files, failed file previews, or file validation errors.',
    width: 128,
    height: 128,
  },
  {
    id: 'flag-th',
    name: 'Thailand Flag',
    fileName: 'flag-th.png',
    src: `${ILLUSTRATION_BASE_PATH}/flag-th.png`,
    alt: 'Thailand flag',
    usage: 'Use for Thailand options in country, market, or currency selectors.',
    width: 216,
    height: 216,
  },
  {
    id: 'flag-us',
    name: 'United States Flag',
    fileName: 'flag-us.png',
    src: `${ILLUSTRATION_BASE_PATH}/flag-us.png`,
    alt: 'United States flag',
    usage: 'Use for United States options in country, market, or currency selectors.',
    width: 216,
    height: 216,
  },
  {
    id: 'flag-ch',
    name: 'Switzerland Flag',
    fileName: 'flag-ch.png',
    src: `${ILLUSTRATION_BASE_PATH}/flag-ch.png`,
    alt: 'Switzerland flag',
    usage: 'Use for Switzerland options in country, market, or currency selectors.',
    width: 216,
    height: 216,
  },
  {
    id: 'flag-au',
    name: 'Australia Flag',
    fileName: 'flag-au.png',
    src: `${ILLUSTRATION_BASE_PATH}/flag-au.png`,
    alt: 'Australia flag',
    usage: 'Use for Australia options in country, market, or currency selectors.',
    width: 216,
    height: 216,
  },
  {
    id: 'flag-hk',
    name: 'Hong Kong Flag',
    fileName: 'flag-hk.png',
    src: `${ILLUSTRATION_BASE_PATH}/flag-hk.png`,
    alt: 'Hong Kong flag',
    usage: 'Use for Hong Kong options in country, market, or currency selectors.',
    width: 216,
    height: 216,
  },
  {
    id: 'flag-jp',
    name: 'Japan Flag',
    fileName: 'flag-jp.png',
    src: `${ILLUSTRATION_BASE_PATH}/flag-jp.png`,
    alt: 'Japan flag',
    usage: 'Use for Japan options in country, market, or currency selectors.',
    width: 216,
    height: 216,
  },
  {
    id: 'flag-kr',
    name: 'Korea Flag',
    fileName: 'flag-kr.png',
    src: `${ILLUSTRATION_BASE_PATH}/flag-kr.png`,
    alt: 'Korea flag',
    usage: 'Use for Korea options in country, market, or currency selectors.',
    width: 216,
    height: 216,
  },
  {
    id: 'flag-vnd',
    name: 'VND Flag',
    fileName: 'flag-vnd.png',
    src: `${ILLUSTRATION_BASE_PATH}/flag-vnd.png`,
    alt: 'VND flag',
    usage: 'Use for VND currency options in currency selectors.',
    width: 216,
    height: 216,
  },
  {
    id: 'flag-nz',
    name: 'New Zealand Flag',
    fileName: 'flag-nz.png',
    src: `${ILLUSTRATION_BASE_PATH}/flag-nz.png`,
    alt: 'New Zealand flag',
    usage: 'Use for New Zealand options in country, market, or currency selectors.',
    width: 216,
    height: 216,
  },
  {
    id: 'flag-eu',
    name: 'European Union Flag',
    fileName: 'flag-eu.png',
    src: `${ILLUSTRATION_BASE_PATH}/flag-eu.png`,
    alt: 'European Union flag',
    usage: 'Use for European Union options in region, market, or currency selectors.',
    width: 216,
    height: 216,
  },
  {
    id: 'flag-ca',
    name: 'Canada Flag',
    fileName: 'flag-ca.png',
    src: `${ILLUSTRATION_BASE_PATH}/flag-ca.png`,
    alt: 'Canada flag',
    usage: 'Use for Canada options in country, market, or currency selectors.',
    width: 216,
    height: 216,
  },
  {
    id: 'flag-gb',
    name: 'United Kingdom Flag',
    fileName: 'flag-gb.png',
    src: `${ILLUSTRATION_BASE_PATH}/flag-gb.png`,
    alt: 'United Kingdom flag',
    usage: 'Use for United Kingdom options in country, market, or currency selectors.',
    width: 216,
    height: 216,
  },
  {
    id: 'flag-cn',
    name: 'China Flag',
    fileName: 'flag-cn.png',
    src: `${ILLUSTRATION_BASE_PATH}/flag-cn.png`,
    alt: 'China flag',
    usage: 'Use for China options in country, market, or currency selectors.',
    width: 216,
    height: 216,
  },
  {
    id: 'flag-sg',
    name: 'Singapore Flag',
    fileName: 'flag-sg.png',
    src: `${ILLUSTRATION_BASE_PATH}/flag-sg.png`,
    alt: 'Singapore flag',
    usage: 'Use for Singapore options in country, market, or currency selectors.',
    width: 216,
    height: 216,
  },
  {
    id: 'notification',
    name: 'Notification',
    fileName: 'notification.png',
    src: `${ILLUSTRATION_BASE_PATH}/notification.png`,
    alt: 'Notification illustration',
    usage: 'Use for notifications, alerts, or message center states.',
    width: 784,
    height: 784,
  },
  {
    id: 'search',
    name: 'Search',
    fileName: 'search.png',
    src: `${ILLUSTRATION_BASE_PATH}/search.png`,
    alt: 'Search illustration',
    usage: 'Use for search empty states or no-result screens.',
    width: 784,
    height: 784,
  },
  {
    id: 'success',
    name: 'Success',
    fileName: 'success.png',
    src: `${ILLUSTRATION_BASE_PATH}/success.png`,
    alt: 'Success illustration',
    usage: 'Use after successful submission, completion, or saved states.',
    width: 784,
    height: 784,
  },
  {
    id: 'unable-to-load-data',
    name: 'Unable To Load Data',
    fileName: 'unable-to-load-data.png',
    src: `${ILLUSTRATION_BASE_PATH}/unable-to-load-data.png`,
    alt: 'Unable to load data illustration',
    usage: 'Use when API data cannot be loaded or refreshed.',
    width: 795,
    height: 784,
  },
  {
    id: 'upload',
    name: 'Upload',
    fileName: 'upload.png',
    src: `${ILLUSTRATION_BASE_PATH}/upload.png`,
    alt: 'Upload illustration',
    usage: 'Use for upload entry points, upload empty states, or file import screens.',
    width: 784,
    height: 784,
  },
  {
    id: 'warning',
    name: 'Warning',
    fileName: 'warning.png',
    src: `${ILLUSTRATION_BASE_PATH}/warning.png`,
    alt: 'Warning illustration',
    usage: 'Use for caution, warning, or recoverable risk states.',
    width: 784,
    height: 784,
  },
];
