export interface PaletteSwatch {
  name: string;
  value: string;
  swatch: string;
  dark?: boolean;
  gradient?: boolean;
}

export interface PaletteColumn {
  id: string;
  title: string;
  swatches: PaletteSwatch[];
}

export const PALETTE_COLUMNS: PaletteColumn[] = [
  {
    id: 'palette-blue',
    title: 'Blue',
    swatches: [
      { name: 'blue-1', value: '#E9EFFF', swatch: '#e9efff' },
      { name: 'blue-2', value: '#DAE4FF', swatch: '#dae4ff' },
      { name: 'blue-3', value: '#A3B7FD', swatch: '#a3b7fd' },
      { name: 'blue-4', value: '#5F7EEB', swatch: '#5f7eeb' },
      { name: 'blue-5', value: '#141ED2', swatch: '#141ed2', dark: true },
      { name: 'blue-6', value: '#121BBB', swatch: '#121bbb', dark: true },
      { name: 'blue-7', value: '#0E16AB', swatch: '#0e16ab', dark: true },
      { name: 'blue-8', value: '#09129B', swatch: '#09129b', dark: true },
      { name: 'blue-9', value: '#050D8C', swatch: '#050d8c', dark: true },
      { name: 'blue-10', value: '#00087C', swatch: '#00087c', dark: true },
    ],
  },
  {
    id: 'palette-purple',
    title: 'Purple',
    swatches: [
      { name: 'purple-1', value: '#F2EBFF', swatch: '#f2ebff' },
      { name: 'purple-2', value: '#DBD3FF', swatch: '#dbd3ff' },
      { name: 'purple-3', value: '#BBADFF', swatch: '#bbadff' },
      { name: 'purple-4', value: '#9781FF', swatch: '#9781ff' },
      { name: 'purple-5', value: '#7B5FFF', swatch: '#7b5fff', dark: true },
      { name: 'purple-6', value: '#6150E1', swatch: '#6150e1', dark: true },
      { name: 'purple-7', value: '#5348D3', swatch: '#5348d3', dark: true },
      { name: 'purple-8', value: '#4641C4', swatch: '#4641c4', dark: true },
      { name: 'purple-9', value: '#3939B5', swatch: '#3939b5', dark: true },
      { name: 'purple-10', value: '#393999', swatch: '#393999', dark: true },
    ],
  },
  {
    id: 'palette-lightblue',
    title: 'Light Blue',
    swatches: [
      { name: 'lightblue-1', value: '#DEF5FF', swatch: '#def5ff' },
      { name: 'lightblue-2', value: '#BDE8FF', swatch: '#bde8ff' },
      { name: 'lightblue-3', value: '#75CEFF', swatch: '#75ceff' },
      { name: 'lightblue-4', value: '#00A5FF', swatch: '#00a5ff' },
      { name: 'lightblue-5', value: '#0075FF', swatch: '#0075ff', dark: true },
      { name: 'lightblue-6', value: '#006AE5', swatch: '#006ae5', dark: true },
      { name: 'lightblue-7', value: '#005FCB', swatch: '#005fcb', dark: true },
      { name: 'lightblue-8', value: '#0054B0', swatch: '#0054b0', dark: true },
      { name: 'lightblue-9', value: '#004996', swatch: '#004996', dark: true },
      { name: 'lightblue-10', value: '#003E7C', swatch: '#003e7c', dark: true },
    ],
  },
  {
    id: 'palette-darkblue',
    title: 'Dark Blue',
    swatches: [
      { name: 'darkblue-1', value: '#FAFDFF', swatch: '#fafdff' },
      { name: 'darkblue-2', value: '#ECF5FA', swatch: '#ecf5fa' },
      { name: 'darkblue-3', value: '#CADBE8', swatch: '#cadbe8' },
      { name: 'darkblue-4', value: '#9BAFC8', swatch: '#9bafc8' },
      { name: 'darkblue-5', value: '#6D83A7', swatch: '#6d83a7' },
      { name: 'darkblue-6', value: '#516682', swatch: '#516682', dark: true },
      { name: 'darkblue-7', value: '#435870', swatch: '#435870', dark: true },
      { name: 'darkblue-8', value: '#354A5E', swatch: '#354a5e', dark: true },
      { name: 'darkblue-9', value: '#273B4B', swatch: '#273b4b', dark: true },
      { name: 'darkblue-10', value: '#192D39', swatch: '#192d39', dark: true },
    ],
  },
  {
    id: 'palette-turquoise',
    title: 'Turquoise',
    swatches: [
      { name: 'turquoise-1', value: '#E7FEFE', swatch: '#e7fefe' },
      { name: 'turquoise-2', value: '#D4FBFB', swatch: '#d4fbfb' },
      { name: 'turquoise-3', value: '#A2F5F5', swatch: '#a2f5f5' },
      { name: 'turquoise-4', value: '#52DDDD', swatch: '#52dddd' },
      { name: 'turquoise-5', value: '#12B7B7', swatch: '#12b7b7', dark: true },
      { name: 'turquoise-6', value: '#0FA4A3', swatch: '#0fa4a3', dark: true },
      { name: 'turquoise-7', value: '#0C908F', swatch: '#0c908f', dark: true },
      { name: 'turquoise-8', value: '#0A7D7C', swatch: '#0a7d7c', dark: true },
      { name: 'turquoise-9', value: '#076968', swatch: '#076968', dark: true },
      { name: 'turquoise-10', value: '#045654', swatch: '#045654', dark: true },
    ],
  },
  {
    id: 'palette-green',
    title: 'Green',
    swatches: [
      { name: 'green-1', value: '#E6F6EC', swatch: '#e6f6ec' },
      { name: 'green-2', value: '#CDFCE9', swatch: '#cdfce9' },
      { name: 'green-3', value: '#85F1C6', swatch: '#85f1c6' },
      { name: 'green-4', value: '#3DD196', swatch: '#3dd196' },
      { name: 'green-5', value: '#00AD68', swatch: '#00ad68', dark: true },
      { name: 'green-6', value: '#009E5F', swatch: '#009e5f', dark: true },
      { name: 'green-7', value: '#008F56', swatch: '#008f56', dark: true },
      { name: 'green-8', value: '#01814E', swatch: '#01814e', dark: true },
      { name: 'green-9', value: '#017245', swatch: '#017245', dark: true },
      { name: 'green-10', value: '#01633C', swatch: '#01633c', dark: true },
    ],
  },
  {
    id: 'palette-orange',
    title: 'Orange',
    swatches: [
      { name: 'orange-1', value: '#FFF4D0', swatch: '#fff4d0' },
      { name: 'orange-2', value: '#FBDE97', swatch: '#fbde97' },
      { name: 'orange-3', value: '#FDC64E', swatch: '#fdc64e' },
      { name: 'orange-4', value: '#F9A500', swatch: '#f9a500' },
      { name: 'orange-5', value: '#FA8A00', swatch: '#fa8a00', dark: true },
      { name: 'orange-6', value: '#DE7A00', swatch: '#de7a00', dark: true },
      { name: 'orange-7', value: '#C36A00', swatch: '#c36a00', dark: true },
      { name: 'orange-8', value: '#A75A00', swatch: '#a75a00', dark: true },
      { name: 'orange-9', value: '#8C4A00', swatch: '#8c4a00', dark: true },
      { name: 'orange-10', value: '#703A00', swatch: '#703a00', dark: true },
    ],
  },
  {
    id: 'palette-red',
    title: 'Red',
    swatches: [
      { name: 'red-1', value: '#FFE3E3', swatch: '#ffe3e3' },
      { name: 'red-2', value: '#FFB1B1', swatch: '#ffb1b1' },
      { name: 'red-3', value: '#FB7070', swatch: '#fb7070' },
      { name: 'red-4', value: '#F34343', swatch: '#f34343' },
      { name: 'red-5', value: '#F00000', swatch: '#f00000', dark: true },
      { name: 'red-6', value: '#D50202', swatch: '#d50202', dark: true },
      { name: 'red-7', value: '#BB0403', swatch: '#bb0403', dark: true },
      { name: 'red-8', value: '#A00705', swatch: '#a00705', dark: true },
      { name: 'red-9', value: '#860906', swatch: '#860906', dark: true },
      { name: 'red-10', value: '#6B0B08', swatch: '#6b0b08', dark: true },
    ],
  },
  {
    id: 'palette-gold',
    title: 'Gold',
    swatches: [
      { name: 'gold-50', value: '#FFF7E9', swatch: '#fff7e9' },
      { name: 'gold-100', value: '#FEE5BA', swatch: '#fee5ba' },
      { name: 'gold-200', value: '#FDD998', swatch: '#fdd998' },
      { name: 'gold-300', value: '#FCC76A', swatch: '#fcc76a' },
      { name: 'gold-400', value: '#FCBD4D', swatch: '#fcbd4d' },
      { name: 'gold-500', value: '#FBAC20', swatch: '#fbac20' },
      { name: 'gold-600', value: '#E49D1D', swatch: '#e49d1d' },
      { name: 'gold-700', value: '#B27A17', swatch: '#b27a17', dark: true },
      { name: 'gold-800', value: '#8A5F12', swatch: '#8a5f12', dark: true },
      { name: 'gold-900', value: '#69480D', swatch: '#69480d', dark: true },
    ],
  },
  {
    id: 'palette-silver',
    title: 'Silver',
    swatches: [
      { name: 'silver-50', value: '#EAEBEC', swatch: '#eaebec' },
      { name: 'silver-100', value: '#BFC2C3', swatch: '#bfc2c3' },
      { name: 'silver-200', value: '#A0A4A6', swatch: '#a0a4a6' },
      { name: 'silver-300', value: '#757B7E', swatch: '#757b7e', dark: true },
      { name: 'silver-400', value: '#5A6165', swatch: '#5a6165', dark: true },
      { name: 'silver-500', value: '#313A3E', swatch: '#313a3e', dark: true },
      { name: 'silver-600', value: '#2D3538', swatch: '#2d3538', dark: true },
      { name: 'silver-700', value: '#23292C', swatch: '#23292c', dark: true },
      { name: 'silver-800', value: '#1B2022', swatch: '#1b2022', dark: true },
      { name: 'silver-900', value: '#15181A', swatch: '#15181a', dark: true },
    ],
  },
  {
    id: 'palette-ocean',
    title: 'Ocean',
    swatches: [
      { name: 'ocean-50', value: '#E7EFF8', swatch: '#e7eff8' },
      { name: 'ocean-100', value: '#B5CEEA', swatch: '#b5ceea' },
      { name: 'ocean-200', value: '#91B6E0', swatch: '#91b6e0' },
      { name: 'ocean-300', value: '#5F94D1', swatch: '#5f94d1' },
      { name: 'ocean-400', value: '#4080C9', swatch: '#4080c9', dark: true },
      { name: 'ocean-500', value: '#1060BB', swatch: '#1060bb', dark: true },
      { name: 'ocean-600', value: '#0F57AA', swatch: '#0f57aa', dark: true },
      { name: 'ocean-700', value: '#0B4485', swatch: '#0b4485', dark: true },
      { name: 'ocean-800', value: '#093567', swatch: '#093567', dark: true },
      { name: 'ocean-900', value: '#07284F', swatch: '#07284f', dark: true },
    ],
  },
  {
    id: 'palette-magenta',
    title: 'Magenta',
    swatches: [
      { name: 'magenta-50', value: '#FCF0FF', swatch: '#fcf0ff' },
      { name: 'magenta-100', value: '#F6D2FF', swatch: '#f6d2ff' },
      { name: 'magenta-200', value: '#F2BCFF', swatch: '#f2bcff' },
      { name: 'magenta-300', value: '#EC9DFE', swatch: '#ec9dfe' },
      { name: 'magenta-400', value: '#E98AFE', swatch: '#e98afe' },
      { name: 'magenta-500', value: '#E36DFE', swatch: '#e36dfe' },
      { name: 'magenta-600', value: '#CF63E7', swatch: '#cf63e7' },
      { name: 'magenta-700', value: '#A14DB4', swatch: '#a14db4', dark: true },
      { name: 'magenta-800', value: '#7D3C8C', swatch: '#7d3c8c', dark: true },
      { name: 'magenta-900', value: '#5F2E6B', swatch: '#5f2e6b', dark: true },
    ],
  },
  {
    id: 'palette-brown',
    title: 'Brown',
    swatches: [
      { name: 'brown-50', value: '#F5F1EC', swatch: '#f5f1ec' },
      { name: 'brown-100', value: '#DFD4C5', swatch: '#dfd4c5' },
      { name: 'brown-200', value: '#CFC0A9', swatch: '#cfc0a9' },
      { name: 'brown-300', value: '#B9A382', swatch: '#b9a382' },
      { name: 'brown-400', value: '#AC916A', swatch: '#ac916a' },
      { name: 'brown-500', value: '#977545', swatch: '#977545', dark: true },
      { name: 'brown-600', value: '#896A3F', swatch: '#896a3f', dark: true },
      { name: 'brown-700', value: '#6B5331', swatch: '#6b5331', dark: true },
      { name: 'brown-800', value: '#534026', swatch: '#534026', dark: true },
      { name: 'brown-900', value: '#3F311D', swatch: '#3f311d', dark: true },
    ],
  },
  {
    id: 'palette-grayscale',
    title: 'Grayscale',
    swatches: [
      { name: 'gray-1', value: '#F3F3F3', swatch: '#f3f3f3' },
      { name: 'gray-2', value: '#D8D8D8', swatch: '#d8d8d8' },
      { name: 'gray-3', value: '#CCCCCC', swatch: '#cccccc' },
      { name: 'gray-4', value: '#9B9B9B', swatch: '#9b9b9b' },
      { name: 'gray-5', value: '#808080', swatch: '#808080', dark: true },
      { name: 'gray-6', value: '#646464', swatch: '#646464', dark: true },
      { name: 'gray-7', value: '#4D4D4D', swatch: '#4d4d4d', dark: true },
      { name: 'gray-8', value: '#2E2E2E', swatch: '#2e2e2e', dark: true },
    ],
  },
  {
    id: 'palette-neutrals',
    title: 'Black / White',
    swatches: [
      { name: 'black-100', value: '#000000', swatch: '#000000', dark: true },
      { name: 'black-50', value: '#00000080', swatch: '#00000080', dark: true },
      { name: 'white-100', value: '#FFFFFF', swatch: '#ffffff' },
      { name: 'white-60', value: '#FFFFFF99', swatch: '#ffffff99' },
      { name: 'white-50', value: '#FFFFFF80', swatch: '#ffffff80' },
      { name: 'white-40', value: '#FFFFFF66', swatch: '#ffffff66' },
      { name: 'white-30', value: '#FFFFFF4D', swatch: '#ffffff4d' },
      { name: 'white-20', value: '#FFFFFF33', swatch: '#ffffff33' },
      { name: 'white-10', value: '#FFFFFF1A', swatch: '#ffffff1a' },
      { name: 'white-5', value: '#FFFFFF0D', swatch: '#ffffff0d' },
    ],
  },
  {
    id: 'palette-gradients',
    title: 'Gradients',
    swatches: [
      {
        name: 'gradient-700',
        value: '#141ED2 → #0075FF',
        swatch: 'linear-gradient(90deg, #141ed2, #0075ff)',
        gradient: true,
      },
      {
        name: 'gradient-600',
        value: '#3949D6 → #2C87F6',
        swatch: 'linear-gradient(90deg, #3949d6, #2c87f6)',
        gradient: true,
      },
      {
        name: 'gradient-500',
        value: '#606AD5 → #569AED',
        swatch: 'linear-gradient(90deg, #606ad5, #569aed)',
        gradient: true,
      },
      {
        name: 'gradient-400',
        value: '#888CD4 → #80AEE5',
        swatch: 'linear-gradient(90deg, #888cd4, #80aee5)',
        gradient: true,
      },
      {
        name: 'gradient-300',
        value: '#AEB1D4 → #AAC1DD',
        swatch: 'linear-gradient(90deg, #aeb1d4, #aac1dd)',
        gradient: true,
      },
      {
        name: 'gradient-200',
        value: '#D6EAF000 → #BDD5E4B2',
        swatch: 'linear-gradient(90deg, #d6eaf000, #bdd5e4b2)',
        gradient: true,
      },
      {
        name: 'gradient-100',
        value: '#141ED2 → #0075FF',
        swatch: 'linear-gradient(90deg, #141ed2, #0075ff)',
        gradient: true,
      },
      {
        name: 'gradient-800',
        value: '#FFFFFF → #F5FFFD → #DDE7FF → #DFE3FF',
        swatch: 'linear-gradient(90deg, #ffffff, #f5fffd, #dde7ff, #dfe3ff)',
        gradient: true,
      },
      { name: 'skyblue-100', value: '#1D5CFB29', swatch: '#1d5cfb29' },
      { name: 'darkblue-50', value: '#ECF5FAB2', swatch: '#ecf5fab2' },
    ],
  },
  {
    id: 'palette-gold-gradients',
    title: 'Gold gradients',
    swatches: [
      {
        name: 'gold-700',
        value: '#CD880D → #FBBA45',
        swatch: 'linear-gradient(90deg, #cd880d, #fbba45)',
        gradient: true,
      },
      {
        name: 'gold-600',
        value: '#D59944 → #FCC260',
        swatch: 'linear-gradient(90deg, #d59944, #fcc260)',
        gradient: true,
      },
      {
        name: 'gold-500',
        value: '#DDAB69 → #FDCC7D',
        swatch: 'linear-gradient(90deg, #ddab69, #fdcc7d)',
        gradient: true,
      },
      {
        name: 'gold-400',
        value: '#E6BF8F → #FED79C',
        swatch: 'linear-gradient(90deg, #e6bf8f, #fed79c)',
        gradient: true,
      },
      {
        name: 'gold-300',
        value: '#EFD5B5 → #FEE3B9',
        swatch: 'linear-gradient(90deg, #efd5b5, #fee3b9)',
        gradient: true,
      },
      {
        name: 'gold-200',
        value: '#FAF1E7 → #FFEBCE',
        swatch: 'linear-gradient(90deg, #faf1e7, #ffebce)',
        gradient: true,
      },
      {
        name: 'gold-100',
        value: '#CD880D → #FBBA45',
        swatch: 'linear-gradient(90deg, #cd880d, #fbba45)',
        gradient: true,
      },
      {
        name: 'gold-800',
        value: '#FFFFFF → #FEFDFA → #F9F0E5 → #FFF3E1',
        swatch: 'linear-gradient(90deg, #ffffff, #fefdfa, #f9f0e5, #fff3e1)',
        gradient: true,
      },
    ],
  },
  {
    id: 'palette-silver-gradients',
    title: 'Silver gradients',
    swatches: [
      {
        name: 'silver-700',
        value: '#313A3E → #757B7E',
        swatch: 'linear-gradient(90deg, #313a3e, #757b7e)',
        gradient: true,
      },
      {
        name: 'silver-600',
        value: '#495255 → #83888B',
        swatch: 'linear-gradient(90deg, #495255, #83888b)',
        gradient: true,
      },
      {
        name: 'silver-500',
        value: '#666D70 → #959A9C',
        swatch: 'linear-gradient(90deg, #666d70, #959a9c)',
        gradient: true,
      },
      {
        name: 'silver-400',
        value: '#898E91 → #ABAFB1',
        swatch: 'linear-gradient(90deg, #898e91, #abafb1)',
        gradient: true,
      },
      {
        name: 'silver-300',
        value: '#AFB3B5 → #C3C5C7',
        swatch: 'linear-gradient(90deg, #afb3b5, #c3c5c7)',
        gradient: true,
      },
      {
        name: 'silver-200',
        value: '#E4E5E6 → #D4D6D7',
        swatch: 'linear-gradient(90deg, #e4e5e6, #d4d6d7)',
        gradient: true,
      },
      {
        name: 'silver-100',
        value: '#313A3E → #757B7E',
        swatch: 'linear-gradient(90deg, #313a3e, #757b7e)',
        gradient: true,
      },
      {
        name: 'silver-800',
        value: '#FFFFFF → #FAFBFB → #E3E4E5 → #E4E5E6',
        swatch: 'linear-gradient(90deg, #ffffff, #fafbfb, #e3e4e5, #e4e5e6)',
        gradient: true,
      },
    ],
  },
  {
    id: 'palette-ocean-gradients',
    title: 'Ocean gradients',
    swatches: [
      {
        name: 'ocean-700',
        value: '#064C9C → #5F9DE4',
        swatch: 'linear-gradient(90deg, #064c9c, #5f9de4)',
        gradient: true,
      },
      {
        name: 'ocean-600',
        value: '#3065AB → #71A8E8',
        swatch: 'linear-gradient(90deg, #3065ab, #71a8e8)',
        gradient: true,
      },
      {
        name: 'ocean-500',
        value: '#547FBB → #87B6EC',
        swatch: 'linear-gradient(90deg, #547fbb, #87b6ec)',
        gradient: true,
      },
      {
        name: 'ocean-400',
        value: '#7C9DCC → #A1C6F1',
        swatch: 'linear-gradient(90deg, #7c9dcc, #a1c6f1)',
        gradient: true,
      },
      {
        name: 'ocean-300',
        value: '#A7BEDE → #BCD6F5',
        swatch: 'linear-gradient(90deg, #a7bede, #bcd6f5)',
        gradient: true,
      },
      {
        name: 'ocean-200',
        value: '#E2E9F4 → #D0E2F9',
        swatch: 'linear-gradient(90deg, #e2e9f4, #d0e2f9)',
        gradient: true,
      },
      {
        name: 'ocean-100',
        value: '#064C9C → #5F9DE4',
        swatch: 'linear-gradient(90deg, #064c9c, #5f9de4)',
        gradient: true,
      },
      {
        name: 'ocean-800',
        value: '#FFFFFF → #FAFBFE → #E0E8F4 → #E1EDFB',
        swatch: 'linear-gradient(90deg, #ffffff, #fafbfe, #e0e8f4, #e1edfb)',
        gradient: true,
      },
    ],
  },
  {
    id: 'palette-magenta-gradients',
    title: 'Magenta gradients',
    swatches: [
      {
        name: 'magenta-700',
        value: '#A013C0 → #E264FE',
        swatch: 'linear-gradient(90deg, #a013c0, #e264fe)',
        gradient: true,
      },
      {
        name: 'magenta-600',
        value: '#AE46CA → #E678FF',
        swatch: 'linear-gradient(90deg, #ae46ca, #e678ff)',
        gradient: true,
      },
      {
        name: 'magenta-500',
        value: '#BE6AD5 → #EB90FF',
        swatch: 'linear-gradient(90deg, #be6ad5, #eb90ff)',
        gradient: true,
      },
      {
        name: 'magenta-400',
        value: '#CE8FE0 → #F1A9FF',
        swatch: 'linear-gradient(90deg, #ce8fe0, #f1a9ff)',
        gradient: true,
      },
      {
        name: 'magenta-300',
        value: '#DFB5EC → #F6C3FF',
        swatch: 'linear-gradient(90deg, #dfb5ec, #f6c3ff)',
        gradient: true,
      },
      {
        name: 'magenta-200',
        value: '#F5E7F9 → #F9D5FF',
        swatch: 'linear-gradient(90deg, #f5e7f9, #f9d5ff)',
        gradient: true,
      },
      {
        name: 'magenta-100',
        value: '#A013C0 → #E264FE',
        swatch: 'linear-gradient(90deg, #a013c0, #e264fe)',
        gradient: true,
      },
      {
        name: 'magenta-800',
        value: '#FFFFFF → #FEFBFF → #F4E5F9 → #FBE5FF',
        swatch: 'linear-gradient(90deg, #ffffff, #fefbff, #f4e5f9, #fbe5ff)',
        gradient: true,
      },
    ],
  },
  {
    id: 'palette-brown-gradients',
    title: 'Brown gradients',
    swatches: [
      {
        name: 'brown-700',
        value: '#7A5420 → #AC916A',
        swatch: 'linear-gradient(90deg, #7a5420, #ac916a)',
        gradient: true,
      },
      {
        name: 'brown-600',
        value: '#8C6A40 → #B59C7A',
        swatch: 'linear-gradient(90deg, #8c6a40, #b59c7a)',
        gradient: true,
      },
      {
        name: 'brown-500',
        value: '#9F8360 → #C0AB8E',
        swatch: 'linear-gradient(90deg, #9f8360, #c0ab8e)',
        gradient: true,
      },
      {
        name: 'brown-400',
        value: '#B69F85 → #CEBDA6',
        swatch: 'linear-gradient(90deg, #b69f85, #cebda6)',
        gradient: true,
      },
      {
        name: 'brown-300',
        value: '#CEBFAD → #DCD0BF',
        swatch: 'linear-gradient(90deg, #cebfad, #dcd0bf)',
        gradient: true,
      },
      {
        name: 'brown-200',
        value: '#EFEAE4 → #E6DED2',
        swatch: 'linear-gradient(90deg, #efeae4, #e6ded2)',
        gradient: true,
      },
      {
        name: 'brown-100',
        value: '#7A5420 → #AC916A',
        swatch: 'linear-gradient(90deg, #7a5420, #ac916a)',
        gradient: true,
      },
      {
        name: 'brown-800',
        value: '#FFFFFF → #FCFBFA → #EEE8E2 → #EFEAE3',
        swatch: 'linear-gradient(90deg, #ffffff, #fcfbfa, #eee8e2, #efeae3)',
        gradient: true,
      },
    ],
  },
  {
    id: 'palette-background-gradients',
    title: 'Background gradients',
    swatches: [
      {
        name: 'page-default',
        value: '#E5D1FF → #DDE7FF → #F5FFFD → #FFFFFF',
        swatch:
          'linear-gradient(330deg, #e5d1ff 7.641%, #dde7ff 37.039%, #f5fffd 70.721%, #ffffff 113.34%)',
        gradient: true,
      },
    ],
  },
];
