export interface SemanticColorTokenMapping {
  alias: string;
  primitive: string;
  value: string;
  category: string;
}

export const SEMANTIC_BACKGROUND_FIGMA_ORDER: readonly string[] = [
  'color/semantic/background/primary',
  'color/semantic/background/secondary',
  'color/semantic/background/tertiary',
  'color/semantic/background/dark',
  'color/semantic/background/brand-primary1',
  'color/semantic/background/brand-primary2',
  'color/semantic/background/brand-primary3',
  'color/semantic/background/brand-primary4',
  'color/semantic/background/brand-primary5',
  'color/semantic/background/brand-secondary1',
  'color/semantic/background/brand-secondary2',
  'color/semantic/background/brand-secondary3',
  'color/semantic/background/brand-secondary4',
  'color/semantic/background/brand-secondary5',
  'color/semantic/background/brand-tertiary1',
  'color/semantic/background/brand-tertiary2',
  'color/semantic/background/brand-tertiary3',
  'color/semantic/background/brand-tertiary4',
  'color/semantic/background/brand-quaternary1',
  'color/semantic/background/brand-quaternary2',
  'color/semantic/background/brand-quaternary3',
  'color/semantic/background/brand-quaternary4',
  'color/semantic/background/brand-quaternary5',
  'color/semantic/background/error-primary',
  'color/semantic/background/error-secondary',
  'color/semantic/background/error-tertiary',
  'color/semantic/background/success-primary',
  'color/semantic/background/success-secondary',
  'color/semantic/background/success-tertiary',
  'color/semantic/background/success-quaternary',
  'color/semantic/background/warning-primary',
  'color/semantic/background/warning-secondary',
  'color/semantic/background/warning-tertiary',
  'color/semantic/background/disable1',
  'color/semantic/background/disable2',
  'color/semantic/background/disable3',
  'color/semantic/background/opacity1',
  'color/semantic/background/opacity2',
  'color/semantic/background/opacity3',
  'color/semantic/background/opacity4',
  'color/semantic/background/opacity5',
  'color/semantic/background/opacity6',
  'color/semantic/background/opacity7',
  'color/semantic/background/black',
  'color/semantic/background/black-secondary',
  'color/semantic/background/gradient1-left',
  'color/semantic/background/gradient1-right',
  'color/semantic/background/gradient2-left',
  'color/semantic/background/gradient2-right',
  'color/semantic/background/gradient3-left',
  'color/semantic/background/gradient3-right',
  'color/semantic/background/gradient4-left',
  'color/semantic/background/gradient4-right',
  'color/semantic/background/gradient5-left',
  'color/semantic/background/gradient5-right',
  'color/semantic/background/gradient6-left',
  'color/semantic/background/gradient6-right',
  'color/semantic/background/gradient8-1',
  'color/semantic/background/gradient8-2',
  'color/semantic/background/gradient8-3',
  'color/semantic/background/gradient8-4',
];

export const SEMANTIC_TEXT_FIGMA_ORDER: readonly string[] = [
  'color/semantic/text/primary',
  'color/semantic/text/primary2',
  'color/semantic/text/primary3',
  'color/semantic/text/primary4',
  'color/semantic/text/secondary',
  'color/semantic/text/tertiary',
  'color/semantic/text/quaternary',
  'color/semantic/text/quaternary2',
  'color/semantic/text/brand-primary1',
  'color/semantic/text/brand-primary2',
  'color/semantic/text/brand-primary3',
  'color/semantic/text/brand-primary4',
  'color/semantic/text/brand-on-primary',
  'color/semantic/text/brand-secondary1',
  'color/semantic/text/brand-secondary2',
  'color/semantic/text/brand-secondary3',
  'color/semantic/text/brand-secondary4',
  'color/semantic/text/brand-on-secondary',
  'color/semantic/text/brand-tertiary1',
  'color/semantic/text/brand-tertiary2',
  'color/semantic/text/on-brand-tertiary',
  'color/semantic/text/error',
  'color/semantic/text/on-error',
  'color/semantic/text/success',
  'color/semantic/text/on-success',
  'color/semantic/text/on-warning',
  'color/semantic/text/disable1',
  'color/semantic/text/disable2',
  'color/semantic/text/disable3',
  'color/semantic/text/disable4',
  'color/semantic/text/white',
];

export const SEMANTIC_BORDER_FIGMA_ORDER: readonly string[] = [
  'color/semantic/border/primary',
  'color/semantic/border/secondary',
  'color/semantic/border/tertiary',
  'color/semantic/border/quaternary',
  'color/semantic/border/quaternary2',
  'color/semantic/border/brand-primary1',
  'color/semantic/border/brand-primary2',
  'color/semantic/border/brand-primary3',
  'color/semantic/border/brand-primary4',
  'color/semantic/border/brand-secondary1',
  'color/semantic/border/brand-secondary2',
  'color/semantic/border/brand-secondary3',
  'color/semantic/border/brand-secondary4',
  'color/semantic/border/brand-tertiary',
  'color/semantic/border/error1',
  'color/semantic/border/error2',
  'color/semantic/border/error3',
  'color/semantic/border/warning',
  'color/semantic/border/success',
  'color/semantic/border/disable1',
  'color/semantic/border/disable2',
];

export const SEMANTIC_ICON_FIGMA_ORDER: readonly string[] = [
  'color/semantic/icon/brand-primary1',
  'color/semantic/icon/brand-primary2',
  'color/semantic/icon/brand-primary3',
  'color/semantic/icon/brand-primary4',
  'color/semantic/icon/brand-on-primary',
  'color/semantic/icon/brand-secondary1',
  'color/semantic/icon/brand-secondary2',
  'color/semantic/icon/brand-secondary3',
  'color/semantic/icon/brand-secondary4',
  'color/semantic/icon/brand-on-secondary',
  'color/semantic/icon/neutral1',
  'color/semantic/icon/neutral2',
  'color/semantic/icon/neutral3',
  'color/semantic/icon/neutral4',
  'color/semantic/icon/neutral5',
  'color/semantic/icon/neutral6',
  'color/semantic/icon/white',
  'color/semantic/icon/success',
  'color/semantic/icon/brand-on-success',
  'color/semantic/icon/error',
  'color/semantic/icon/brand-on-error',
  'color/semantic/icon/warning',
  'color/semantic/icon/brand-on-warning',
  'color/semantic/icon/disable1',
  'color/semantic/icon/disable2',
  'color/semantic/icon/disable3',
  'color/semantic/icon/disable4',
];

export const SEMANTIC_COLOR_TOKEN_MAPPINGS: SemanticColorTokenMapping[] = [
  { alias: "color/semantic/background/black", primitive: "color/primitive/black/100%", value: "#000000", category: "background" },
  { alias: "color/semantic/background/black-secondary", primitive: "color/primitive/black/50%", value: "#00000080", category: "background" },
  { alias: "color/semantic/background/brand-primary1", primitive: "color/primitive/blue/500", value: "#141ED2", category: "background" },
  { alias: "color/semantic/background/brand-primary2", primitive: "color/primitive/blue/400", value: "#5F7EEB", category: "background" },
  { alias: "color/semantic/background/brand-primary3", primitive: "color/primitive/blue/300", value: "#A3B7FD", category: "background" },
  { alias: "color/semantic/background/brand-primary4", primitive: "color/primitive/blue/200", value: "#DAE4FF", category: "background" },
  { alias: "color/semantic/background/brand-primary5", primitive: "color/primitive/blue/100", value: "#E9EFFF", category: "background" },
  { alias: "color/semantic/background/brand-quaternary1", primitive: "color/primitive/darkblue/500", value: "#6D83A7", category: "background" },
  { alias: "color/semantic/background/brand-quaternary2", primitive: "color/primitive/darkblue/300", value: "#CADBE8", category: "background" },
  { alias: "color/semantic/background/brand-quaternary3", primitive: "color/primitive/darkblue/200", value: "#ECF5FA", category: "background" },
  { alias: "color/semantic/background/brand-quaternary4", primitive: "color/primitive/darkblue/100", value: "#FAFDFF", category: "background" },
  { alias: "color/semantic/background/brand-quaternary5", primitive: "color/primitive/darkblue/400", value: "#9BAFC8", category: "background" },
  { alias: "color/semantic/background/brand-secondary1", primitive: "color/primitive/purple/500", value: "#7B5FFF", category: "background" },
  { alias: "color/semantic/background/brand-secondary2", primitive: "color/primitive/purple/400", value: "#9781FF", category: "background" },
  { alias: "color/semantic/background/brand-secondary3", primitive: "color/primitive/purple/300", value: "#BBADFF", category: "background" },
  { alias: "color/semantic/background/brand-secondary4", primitive: "color/primitive/purple/200", value: "#DBD3FF", category: "background" },
  { alias: "color/semantic/background/brand-secondary5", primitive: "color/primitive/purple/100", value: "#F2EBFF", category: "background" },
  { alias: "color/semantic/background/brand-tertiary1", primitive: "color/primitive/turquoise/500", value: "#12B7B7", category: "background" },
  { alias: "color/semantic/background/brand-tertiary2", primitive: "color/primitive/turquoise/400", value: "#52DDDD", category: "background" },
  { alias: "color/semantic/background/brand-tertiary3", primitive: "color/primitive/turquoise/300", value: "#A2F5F5", category: "background" },
  { alias: "color/semantic/background/brand-tertiary4", primitive: "color/primitive/turquoise/200", value: "#D4FBFB", category: "background" },
  { alias: "color/semantic/background/dark", primitive: "color/primitive/blue/700", value: "#0E16AB", category: "background" },
  { alias: "color/semantic/background/disable1", primitive: "color/primitive/grayscale/400", value: "#CCCCCC", category: "background" },
  { alias: "color/semantic/background/disable2", primitive: "color/primitive/grayscale/300", value: "#D8D8D8", category: "background" },
  { alias: "color/semantic/background/disable3", primitive: "color/primitive/grayscale/200", value: "#F3F3F3", category: "background" },
  { alias: "color/semantic/background/error-primary", primitive: "color/primitive/red/500", value: "#F00000", category: "background" },
  { alias: "color/semantic/background/error-secondary", primitive: "color/primitive/red/400", value: "#F34343", category: "background" },
  { alias: "color/semantic/background/error-tertiary", primitive: "color/primitive/red/100", value: "#FFE3E3", category: "background" },
  { alias: "color/semantic/background/gradient1-left", primitive: "color/primitive/gradient/700/1", value: "#141ED2", category: "background" },
  { alias: "color/semantic/background/gradient1-right", primitive: "color/primitive/gradient/700/2", value: "#0075FF", category: "background" },
  { alias: "color/semantic/background/gradient2-left", primitive: "color/primitive/gradient/600/1", value: "#3949D6", category: "background" },
  { alias: "color/semantic/background/gradient2-right", primitive: "color/primitive/gradient/600/2", value: "#2C87F6", category: "background" },
  { alias: "color/semantic/background/gradient3-left", primitive: "color/primitive/gradient/500/1", value: "#606AD5", category: "background" },
  { alias: "color/semantic/background/gradient3-right", primitive: "color/primitive/gradient/500/2", value: "#569AED", category: "background" },
  { alias: "color/semantic/background/gradient4-left", primitive: "color/primitive/gradient/500/1", value: "#606AD5", category: "background" },
  { alias: "color/semantic/background/gradient4-right", primitive: "color/primitive/gradient/500/2", value: "#569AED", category: "background" },
  { alias: "color/semantic/background/gradient5-left", primitive: "color/primitive/gradient/300/1", value: "#AEB1D4", category: "background" },
  { alias: "color/semantic/background/gradient5-right", primitive: "color/primitive/gradient/300/2", value: "#AAC1DD", category: "background" },
  { alias: "color/semantic/background/gradient6-left", primitive: "color/primitive/gradient/100/1", value: "#141ED2", category: "background" },
  { alias: "color/semantic/background/gradient6-right", primitive: "color/primitive/gradient/100/2", value: "#0075FF", category: "background" },
  { alias: "color/semantic/background/gradient8-1", primitive: "color/primitive/gradient/800/1", value: "#FFFFFF", category: "background" },
  { alias: "color/semantic/background/gradient8-2", primitive: "color/primitive/gradient/800/2", value: "#F5FFFD", category: "background" },
  { alias: "color/semantic/background/gradient8-3", primitive: "color/primitive/gradient/800/3", value: "#DDE7FF", category: "background" },
  { alias: "color/semantic/background/gradient8-4", primitive: "color/primitive/gradient/800/4", value: "#DFE3FF", category: "background" },
  { alias: "color/semantic/background/opacity1", primitive: "color/primitive/white/60%", value: "#FFFFFF99", category: "background" },
  { alias: "color/semantic/background/opacity2", primitive: "color/primitive/white/50%", value: "#FFFFFF80", category: "background" },
  { alias: "color/semantic/background/opacity3", primitive: "color/primitive/white/40%", value: "#FFFFFF66", category: "background" },
  { alias: "color/semantic/background/opacity4", primitive: "color/primitive/white/30%", value: "#FFFFFF4D", category: "background" },
  { alias: "color/semantic/background/opacity5", primitive: "color/primitive/white/20%", value: "#FFFFFF33", category: "background" },
  { alias: "color/semantic/background/opacity6", primitive: "color/primitive/white/10%", value: "#FFFFFF1A", category: "background" },
  { alias: "color/semantic/background/opacity7", primitive: "color/primitive/white/5%", value: "#FFFFFF0D", category: "background" },
  { alias: "color/semantic/background/primary", primitive: "color/primitive/white/100%", value: "#FFFFFF", category: "background" },
  { alias: "color/semantic/background/secondary", primitive: "color/primitive/darkblue/200", value: "#ECF5FA", category: "background" },
  { alias: "color/semantic/background/success-primary", primitive: "color/primitive/green/500", value: "#00AD68", category: "background" },
  { alias: "color/semantic/background/success-quaternary", primitive: "color/primitive/green/100", value: "#E6F6EC", category: "background" },
  { alias: "color/semantic/background/success-secondary", primitive: "color/primitive/green/400", value: "#3DD196", category: "background" },
  { alias: "color/semantic/background/success-tertiary", primitive: "color/primitive/green/300", value: "#85F1C6", category: "background" },
  { alias: "color/semantic/background/tertiary", primitive: "color/primitive/lightblue/700", value: "#005FCB", category: "background" },
  { alias: "color/semantic/background/warning-primary", primitive: "color/primitive/orange/500", value: "#FA8A00", category: "background" },
  { alias: "color/semantic/background/warning-secondary", primitive: "color/primitive/orange/300", value: "#FDC64E", category: "background" },
  { alias: "color/semantic/background/warning-tertiary", primitive: "color/primitive/orange/100", value: "#FFF4D0", category: "background" },
  { alias: "color/semantic/blur/1", primitive: "color/primitive/lightblue/300", value: "#75CEFF", category: "blur" },
  { alias: "color/semantic/border/brand-primary1", primitive: "color/primitive/blue/500", value: "#141ED2", category: "border" },
  { alias: "color/semantic/border/brand-primary2", primitive: "color/primitive/blue/400", value: "#5F7EEB", category: "border" },
  { alias: "color/semantic/border/brand-primary3", primitive: "color/primitive/blue/300", value: "#A3B7FD", category: "border" },
  { alias: "color/semantic/border/brand-primary4", primitive: "color/primitive/blue/200", value: "#DAE4FF", category: "border" },
  { alias: "color/semantic/border/brand-secondary1", primitive: "color/primitive/purple/500", value: "#7B5FFF", category: "border" },
  { alias: "color/semantic/border/brand-secondary2", primitive: "color/primitive/purple/400", value: "#9781FF", category: "border" },
  { alias: "color/semantic/border/brand-secondary3", primitive: "color/primitive/purple/300", value: "#BBADFF", category: "border" },
  { alias: "color/semantic/border/brand-secondary4", primitive: "color/primitive/purple/200", value: "#DBD3FF", category: "border" },
  { alias: "color/semantic/border/brand-tertiary", primitive: "color/primitive/turquoise/400", value: "#52DDDD", category: "border" },
  { alias: "color/semantic/border/disable1", primitive: "color/primitive/grayscale/500", value: "#9B9B9B", category: "border" },
  { alias: "color/semantic/border/disable2", primitive: "color/primitive/grayscale/400", value: "#CCCCCC", category: "border" },
  { alias: "color/semantic/border/error1", primitive: "color/primitive/red/500", value: "#F00000", category: "border" },
  { alias: "color/semantic/border/error2", primitive: "color/primitive/red/400", value: "#F34343", category: "border" },
  { alias: "color/semantic/border/error3", primitive: "color/primitive/red/300", value: "#FB7070", category: "border" },
  { alias: "color/semantic/border/primary", primitive: "color/primitive/blue/200", value: "#DAE4FF", category: "border" },
  { alias: "color/semantic/border/quaternary", primitive: "color/primitive/darkblue/300", value: "#CADBE8", category: "border" },
  { alias: "color/semantic/border/quaternary2", primitive: "color/primitive/darkblue/200", value: "#ECF5FA", category: "border" },
  { alias: "color/semantic/border/secondary", primitive: "color/primitive/darkblue/500", value: "#6D83A7", category: "border" },
  { alias: "color/semantic/border/success", primitive: "color/primitive/green/300", value: "#85F1C6", category: "border" },
  { alias: "color/semantic/border/tertiary", primitive: "color/primitive/darkblue/400", value: "#9BAFC8", category: "border" },
  { alias: "color/semantic/border/warning", primitive: "color/primitive/orange/300", value: "#FDC64E", category: "border" },
  { alias: "color/semantic/chart/1", primitive: "color/primitive/blue/500", value: "#141ED2", category: "chart" },
  { alias: "color/semantic/chart/10", primitive: "color/primitive/purple/300", value: "#BBADFF", category: "chart" },
  { alias: "color/semantic/chart/11", primitive: "color/primitive/turquoise/800", value: "#0A7D7C", category: "chart" },
  { alias: "color/semantic/chart/12", primitive: "color/primitive/orange/300", value: "#FDC64E", category: "chart" },
  { alias: "color/semantic/chart/13", primitive: "color/primitive/green/300", value: "#85F1C6", category: "chart" },
  { alias: "color/semantic/chart/14", primitive: "color/primitive/darkblue/400", value: "#9BAFC8", category: "chart" },
  { alias: "color/semantic/chart/15", primitive: "color/primitive/blue/300", value: "#A3B7FD", category: "chart" },
  { alias: "color/semantic/chart/16", primitive: "color/primitive/purple/200", value: "#DBD3FF", category: "chart" },
  { alias: "color/semantic/chart/17", primitive: "color/primitive/lightblue/200", value: "#BDE8FF", category: "chart" },
  { alias: "color/semantic/chart/18", primitive: "color/primitive/turquoise/200", value: "#D4FBFB", category: "chart" },
  { alias: "color/semantic/chart/19", primitive: "color/primitive/orange/200", value: "#FBDE97", category: "chart" },
  { alias: "color/semantic/chart/2", primitive: "color/primitive/purple/500", value: "#7B5FFF", category: "chart" },
  { alias: "color/semantic/chart/20", primitive: "color/primitive/grayscale/300", value: "#D8D8D8", category: "chart" },
  { alias: "color/semantic/chart/3", primitive: "color/primitive/turquoise/400", value: "#52DDDD", category: "chart" },
  { alias: "color/semantic/chart/4", primitive: "color/primitive/orange/500", value: "#FA8A00", category: "chart" },
  { alias: "color/semantic/chart/5", primitive: "color/primitive/lightblue/500", value: "#0075FF", category: "chart" },
  { alias: "color/semantic/chart/6", primitive: "color/primitive/green/500", value: "#00AD68", category: "chart" },
  { alias: "color/semantic/chart/7", primitive: "color/primitive/darkblue/1000", value: "#192D39", category: "chart" },
  { alias: "color/semantic/chart/8", primitive: "color/primitive/darkblue/800", value: "#354A5E", category: "chart" },
  { alias: "color/semantic/chart/9", primitive: "color/primitive/lightblue/300", value: "#75CEFF", category: "chart" },
  { alias: "color/semantic/divider/primary", primitive: "color/primitive/blue/200", value: "#DAE4FF", category: "divider" },
  { alias: "color/semantic/hyperlink/disable", primitive: "color/primitive/grayscale/500", value: "#9B9B9B", category: "hyperlink" },
  { alias: "color/semantic/hyperlink/primary", primitive: "color/primitive/blue/500", value: "#141ED2", category: "hyperlink" },
  { alias: "color/semantic/icon/brand-on-error", primitive: "color/primitive/white/100%", value: "#FFFFFF", category: "icon" },
  { alias: "color/semantic/icon/brand-on-primary", primitive: "color/primitive/white/100%", value: "#FFFFFF", category: "icon" },
  { alias: "color/semantic/icon/brand-on-secondary", primitive: "color/primitive/white/100%", value: "#FFFFFF", category: "icon" },
  { alias: "color/semantic/icon/brand-on-success", primitive: "color/primitive/white/100%", value: "#FFFFFF", category: "icon" },
  { alias: "color/semantic/icon/brand-on-warning", primitive: "color/primitive/white/100%", value: "#FFFFFF", category: "icon" },
  { alias: "color/semantic/icon/brand-primary1", primitive: "color/primitive/blue/500", value: "#141ED2", category: "icon" },
  { alias: "color/semantic/icon/brand-primary2", primitive: "color/primitive/blue/400", value: "#5F7EEB", category: "icon" },
  { alias: "color/semantic/icon/brand-primary3", primitive: "color/primitive/blue/300", value: "#A3B7FD", category: "icon" },
  { alias: "color/semantic/icon/brand-primary4", primitive: "color/primitive/blue/200", value: "#DAE4FF", category: "icon" },
  { alias: "color/semantic/icon/brand-secondary1", primitive: "color/primitive/purple/500", value: "#7B5FFF", category: "icon" },
  { alias: "color/semantic/icon/brand-secondary2", primitive: "color/primitive/purple/400", value: "#9781FF", category: "icon" },
  { alias: "color/semantic/icon/brand-secondary3", primitive: "color/primitive/purple/300", value: "#BBADFF", category: "icon" },
  { alias: "color/semantic/icon/brand-secondary4", primitive: "color/primitive/purple/200", value: "#DBD3FF", category: "icon" },
  { alias: "color/semantic/icon/disable1", primitive: "color/primitive/grayscale/600", value: "#808080", category: "icon" },
  { alias: "color/semantic/icon/disable2", primitive: "color/primitive/grayscale/500", value: "#9B9B9B", category: "icon" },
  { alias: "color/semantic/icon/disable3", primitive: "color/primitive/grayscale/400", value: "#CCCCCC", category: "icon" },
  { alias: "color/semantic/icon/disable4", primitive: "color/primitive/grayscale/200", value: "#F3F3F3", category: "icon" },
  { alias: "color/semantic/icon/error", primitive: "color/primitive/red/500", value: "#F00000", category: "icon" },
  { alias: "color/semantic/icon/neutral1", primitive: "color/primitive/darkblue/1000", value: "#192D39", category: "icon" },
  { alias: "color/semantic/icon/neutral2", primitive: "color/primitive/darkblue/800", value: "#354A5E", category: "icon" },
  { alias: "color/semantic/icon/neutral3", primitive: "color/primitive/darkblue/700", value: "#435870", category: "icon" },
  { alias: "color/semantic/icon/neutral4", primitive: "color/primitive/darkblue/500", value: "#6D83A7", category: "icon" },
  { alias: "color/semantic/icon/neutral5", primitive: "color/primitive/darkblue/400", value: "#9BAFC8", category: "icon" },
  { alias: "color/semantic/icon/neutral6", primitive: "color/primitive/darkblue/50", value: "#ECF5FAB2", category: "icon" },
  { alias: "color/semantic/icon/success", primitive: "color/primitive/green/500", value: "#00AD68", category: "icon" },
  { alias: "color/semantic/icon/warning", primitive: "color/primitive/orange/500", value: "#FA8A00", category: "icon" },
  { alias: "color/semantic/icon/white", primitive: "color/primitive/white/100%", value: "#FFFFFF", category: "icon" },
  { alias: "color/semantic/overlay/primary", primitive: "color/primitive/black/50%", value: "#00000080", category: "overlay" },
  { alias: "color/semantic/shadow/1", primitive: "color/primitive/skyblue/100", value: "#1D5CFB29", category: "shadow" },
  { alias: "color/semantic/shadow/2", primitive: "color/primitive/skyblue/100", value: "#1D5CFB29", category: "shadow" },
  { alias: "color/semantic/shadow/3", primitive: "color/primitive/skyblue/100", value: "#1D5CFB29", category: "shadow" },
  { alias: "color/semantic/shadow/4", primitive: "color/primitive/skyblue/100", value: "#1D5CFB29", category: "shadow" },
  { alias: "color/semantic/shadow/5", primitive: "color/primitive/skyblue/100", value: "#1D5CFB29", category: "shadow" },
  { alias: "color/semantic/skeleton/primary", primitive: "color/primitive/grayscale/300", value: "#D8D8D8", category: "skeleton" },
  { alias: "color/semantic/skeleton/secondary", primitive: "color/primitive/grayscale/200", value: "#F3F3F3", category: "skeleton" },
  { alias: "color/semantic/text/brand-on-primary", primitive: "color/primitive/white/100%", value: "#FFFFFF", category: "text" },
  { alias: "color/semantic/text/brand-on-secondary", primitive: "color/primitive/white/100%", value: "#FFFFFF", category: "text" },
  { alias: "color/semantic/text/brand-primary1", primitive: "color/primitive/blue/500", value: "#141ED2", category: "text" },
  { alias: "color/semantic/text/brand-primary2", primitive: "color/primitive/blue/400", value: "#5F7EEB", category: "text" },
  { alias: "color/semantic/text/brand-primary3", primitive: "color/primitive/blue/300", value: "#A3B7FD", category: "text" },
  { alias: "color/semantic/text/brand-primary4", primitive: "color/primitive/blue/200", value: "#DAE4FF", category: "text" },
  { alias: "color/semantic/text/brand-secondary1", primitive: "color/primitive/purple/500", value: "#7B5FFF", category: "text" },
  { alias: "color/semantic/text/brand-secondary2", primitive: "color/primitive/purple/400", value: "#9781FF", category: "text" },
  { alias: "color/semantic/text/brand-secondary3", primitive: "color/primitive/purple/300", value: "#BBADFF", category: "text" },
  { alias: "color/semantic/text/brand-secondary4", primitive: "color/primitive/purple/200", value: "#DBD3FF", category: "text" },
  { alias: "color/semantic/text/brand-tertiary1", primitive: "color/primitive/turquoise/500", value: "#12B7B7", category: "text" },
  { alias: "color/semantic/text/brand-tertiary2", primitive: "color/primitive/turquoise/400", value: "#52DDDD", category: "text" },
  { alias: "color/semantic/text/disable1", primitive: "color/primitive/grayscale/600", value: "#808080", category: "text" },
  { alias: "color/semantic/text/disable2", primitive: "color/primitive/grayscale/500", value: "#9B9B9B", category: "text" },
  { alias: "color/semantic/text/disable3", primitive: "color/primitive/grayscale/200", value: "#F3F3F3", category: "text" },
  { alias: "color/semantic/text/disable4", primitive: "color/primitive/grayscale/400", value: "#CCCCCC", category: "text" },
  { alias: "color/semantic/text/error", primitive: "color/primitive/red/400", value: "#F34343", category: "text" },
  { alias: "color/semantic/text/on-brand-tertiary", primitive: "color/primitive/darkblue/1000", value: "#192D39", category: "text" },
  { alias: "color/semantic/text/on-error", primitive: "color/primitive/white/100%", value: "#FFFFFF", category: "text" },
  { alias: "color/semantic/text/on-success", primitive: "color/primitive/white/100%", value: "#FFFFFF", category: "text" },
  { alias: "color/semantic/text/on-warning", primitive: "color/primitive/orange/500", value: "#FA8A00", category: "text" },
  { alias: "color/semantic/text/primary", primitive: "color/primitive/darkblue/1000", value: "#192D39", category: "text" },
  { alias: "color/semantic/text/primary2", primitive: "color/primitive/darkblue/800", value: "#354A5E", category: "text" },
  { alias: "color/semantic/text/primary3", primitive: "color/primitive/darkblue/700", value: "#435870", category: "text" },
  { alias: "color/semantic/text/primary4", primitive: "color/primitive/darkblue/600", value: "#516682", category: "text" },
  { alias: "color/semantic/text/quaternary", primitive: "color/primitive/darkblue/300", value: "#CADBE8", category: "text" },
  { alias: "color/semantic/text/quaternary2", primitive: "color/primitive/darkblue/50", value: "#ECF5FAB2", category: "text" },
  { alias: "color/semantic/text/secondary", primitive: "color/primitive/darkblue/500", value: "#6D83A7", category: "text" },
  { alias: "color/semantic/text/success", primitive: "color/primitive/green/500", value: "#00AD68", category: "text" },
  { alias: "color/semantic/text/tertiary", primitive: "color/primitive/darkblue/400", value: "#9BAFC8", category: "text" },
  { alias: "color/semantic/text/white", primitive: "color/primitive/white/100%", value: "#FFFFFF", category: "text" },
];
