export interface TypographyStyleRow {
  name: string;
  className: string;
  fontSize: string;
  lineHeight: string;
  weight: string;
  letterSpacing: string;
  textCase: string;
  textDecoration: string;
  sample: string;
}

export interface TypographyStyleGroup {
  title: string;
  id: string;
  rows: TypographyStyleRow[];
}

const SAMPLE = 'The quick brown fox jumps over the lazy dog — 0123456789';

export const TYPOGRAPHY_STYLE_GROUPS: TypographyStyleGroup[] = [
  {
    title: 'H1',
    id: 'typography-font-h1',
    rows: [
      {
        name: 'H1/Normal/24-Regular',
        className: 'mbbiz-typo-h1-normal-24-regular',
        fontSize: '24px',
        lineHeight: '32px',
        weight: 'Regular (400)',
        letterSpacing: '0.25px',
        textCase: 'Original',
        textDecoration: 'None',
        sample: SAMPLE,
      },
      {
        name: 'H1/Normal/24-Semibold',
        className: 'mbbiz-typo-h1-normal-24-semibold',
        fontSize: '24px',
        lineHeight: '32px',
        weight: 'Semibold (600)',
        letterSpacing: '0.25px',
        textCase: 'Original',
        textDecoration: 'None',
        sample: SAMPLE,
      },
      {
        name: 'H1/Uppercase/24-Regular',
        className: 'mbbiz-typo-h1-uppercase-24-regular',
        fontSize: '24px',
        lineHeight: '32px',
        weight: 'Regular (400)',
        letterSpacing: '0.25px',
        textCase: 'Uppercase',
        textDecoration: 'None',
        sample: SAMPLE,
      },
      {
        name: 'H1/Strikethrough/24-Regular',
        className: 'mbbiz-typo-h1-strikethrough-24-regular',
        fontSize: '24px',
        lineHeight: '32px',
        weight: 'Regular (400)',
        letterSpacing: '0.25px',
        textCase: 'Original',
        textDecoration: 'Strikethrough',
        sample: SAMPLE,
      },
    ],
  },
  {
    title: 'H2',
    id: 'typography-font-h2',
    rows: [
      {
        name: 'H2/Normal/20-Regular',
        className: 'mbbiz-typo-h2-normal-20-regular',
        fontSize: '20px',
        lineHeight: '28px',
        weight: 'Regular (400)',
        letterSpacing: '0.25px',
        textCase: 'Original',
        textDecoration: 'None',
        sample: SAMPLE,
      },
      {
        name: 'H2/Normal/20-Semibold',
        className: 'mbbiz-typo-h2-normal-20-semibold',
        fontSize: '20px',
        lineHeight: '28px',
        weight: 'Semibold (600)',
        letterSpacing: '0.25px',
        textCase: 'Original',
        textDecoration: 'None',
        sample: SAMPLE,
      },
      {
        name: 'H2/Uppercase/20-Regular',
        className: 'mbbiz-typo-h2-uppercase-20-regular',
        fontSize: '20px',
        lineHeight: '28px',
        weight: 'Regular (400)',
        letterSpacing: '0.25px',
        textCase: 'Uppercase',
        textDecoration: 'None',
        sample: SAMPLE,
      },
      {
        name: 'H2/Strikethrough/20-Regular',
        className: 'mbbiz-typo-h2-strikethrough-20-regular',
        fontSize: '20px',
        lineHeight: '28px',
        weight: 'Regular (400)',
        letterSpacing: '0.25px',
        textCase: 'Original',
        textDecoration: 'Strikethrough',
        sample: SAMPLE,
      },
    ],
  },
  {
    title: 'H2 / Sub-Header',
    id: 'typography-font-h2-sub-header',
    rows: [
      {
        name: 'H2/Sub-Header/Normal/16-Regular',
        className: 'mbbiz-typo-h2-sub-header-normal-16-regular',
        fontSize: '16px',
        lineHeight: '24px',
        weight: 'Regular (400)',
        letterSpacing: '0.25px',
        textCase: 'Original',
        textDecoration: 'None',
        sample: SAMPLE,
      },
      {
        name: 'H2/Sub-Header/Normal/16-SemiBold',
        className: 'mbbiz-typo-h2-sub-header-normal-16-semibold',
        fontSize: '16px',
        lineHeight: '24px',
        weight: 'Semibold (600)',
        letterSpacing: '0.25px',
        textCase: 'Original',
        textDecoration: 'None',
        sample: SAMPLE,
      },
      {
        name: 'H2/Sub-Header/Uppercase/16-Regular',
        className: 'mbbiz-typo-h2-sub-header-uppercase-16-regular',
        fontSize: '16px',
        lineHeight: '24px',
        weight: 'Regular (400)',
        letterSpacing: '0.25px',
        textCase: 'Uppercase',
        textDecoration: 'None',
        sample: SAMPLE,
      },
      {
        name: 'H2/Sub-Header/Strikethrough/16-Regular',
        className: 'mbbiz-typo-h2-sub-header-strikethrough-16-regular',
        fontSize: '16px',
        lineHeight: '24px',
        weight: 'Regular (400)',
        letterSpacing: '0.25px',
        textCase: 'Original',
        textDecoration: 'Strikethrough',
        sample: SAMPLE,
      },
      {
        name: 'H2/Sub-Header/Underline/16-SemiBold',
        className: 'mbbiz-typo-h2-sub-header-underline-16-semibold',
        fontSize: '16px',
        lineHeight: '24px',
        weight: 'Semibold (600)',
        letterSpacing: '0.25px',
        textCase: 'Original',
        textDecoration: 'Underline',
        sample: SAMPLE,
      },
      {
        name: 'H2/Sub-Header/Underline/16-Regular',
        className: 'mbbiz-typo-h2-sub-header-underline-16-regular',
        fontSize: '16px',
        lineHeight: '24px',
        weight: 'Regular (400)',
        letterSpacing: '0.5px',
        textCase: 'Original',
        textDecoration: 'Underline',
        sample: SAMPLE,
      },
    ],
  },
  {
    title: 'H3',
    id: 'typography-font-h3',
    rows: [
      {
        name: 'H3/Normal/14-SemiBold',
        className: 'mbbiz-typo-h3-normal-14-semibold',
        fontSize: '14px',
        lineHeight: '20px',
        weight: 'Semibold (600)',
        letterSpacing: '0.25px',
        textCase: 'Original',
        textDecoration: 'None',
        sample: SAMPLE,
      },
      {
        name: 'H3/Uppercase/14-SemiBold',
        className: 'mbbiz-typo-h3-uppercase-14-semibold',
        fontSize: '14px',
        lineHeight: '20px',
        weight: 'Semibold (600)',
        letterSpacing: '0.25px',
        textCase: 'Uppercase',
        textDecoration: 'None',
        sample: SAMPLE,
      },
      {
        name: 'H3/Strikethrough/14-SemiBold',
        className: 'mbbiz-typo-h3-strikethrough-14-semibold',
        fontSize: '14px',
        lineHeight: '20px',
        weight: 'Semibold (600)',
        letterSpacing: '0.25px',
        textCase: 'Original',
        textDecoration: 'Strikethrough',
        sample: SAMPLE,
      },
    ],
  },
  {
    title: 'Body Copy (Data & Nav)',
    id: 'typography-font-body',
    rows: [
      {
        name: 'Body Copy (Data & Nav)/Normal/14-Regular',
        className: 'mbbiz-typo-body-normal-14-regular',
        fontSize: '14px',
        lineHeight: '20px',
        weight: 'Regular (400)',
        letterSpacing: '0.25px',
        textCase: 'Original',
        textDecoration: 'None',
        sample: SAMPLE,
      },
      {
        name: 'Body Copy (Data & Nav)/Uppercase/14-Regular',
        className: 'mbbiz-typo-body-uppercase-14-regular',
        fontSize: '14px',
        lineHeight: '20px',
        weight: 'Regular (400)',
        letterSpacing: '0.25px',
        textCase: 'Uppercase',
        textDecoration: 'None',
        sample: SAMPLE,
      },
      {
        name: 'Body Copy (Data & Nav)/Strikethrough/14-Regular',
        className: 'mbbiz-typo-body-strikethrough-14-regular',
        fontSize: '14px',
        lineHeight: '20px',
        weight: 'Regular (400)',
        letterSpacing: '0.25px',
        textCase: 'Original',
        textDecoration: 'Strikethrough',
        sample: SAMPLE,
      },
      {
        name: 'Body Copy (Data & Nav)/Underline/14-SemiBold',
        className: 'mbbiz-typo-body-underline-14-semibold',
        fontSize: '14px',
        lineHeight: '20px',
        weight: 'Semibold (600)',
        letterSpacing: '0',
        textCase: 'Original',
        textDecoration: 'Underline',
        sample: SAMPLE,
      },
      {
        name: 'Body Copy (Data & Nav)/Underline/14-Regular',
        className: 'mbbiz-typo-body-underline-14-regular',
        fontSize: '14px',
        lineHeight: '20px',
        weight: 'Regular (400)',
        letterSpacing: '0',
        textCase: 'Original',
        textDecoration: 'Underline',
        sample: SAMPLE,
      },
      {
        name: 'Body Copy (Data & Nav)/Normal/12-Regular',
        className: 'mbbiz-typo-body-normal-12-regular',
        fontSize: '12px',
        lineHeight: '16px',
        weight: 'Regular (400)',
        letterSpacing: '0.25px',
        textCase: 'Original',
        textDecoration: 'None',
        sample: SAMPLE,
      },
      {
        name: 'Body Copy (Data & Nav)/Normal/12-Semibold',
        className: 'mbbiz-typo-body-normal-12-semibold',
        fontSize: '12px',
        lineHeight: '16px',
        weight: 'Semibold (600)',
        letterSpacing: '0.25px',
        textCase: 'Original',
        textDecoration: 'None',
        sample: SAMPLE,
      },
      {
        name: 'Body Copy (Data & Nav)/Uppercase/12-Regular',
        className: 'mbbiz-typo-body-uppercase-12-regular',
        fontSize: '12px',
        lineHeight: '16px',
        weight: 'Regular (400)',
        letterSpacing: '0.25px',
        textCase: 'Uppercase',
        textDecoration: 'None',
        sample: SAMPLE,
      },
      {
        name: 'Body Copy (Data & Nav)/Strikethrough/12-Regular',
        className: 'mbbiz-typo-body-strikethrough-12-regular',
        fontSize: '12px',
        lineHeight: '16px',
        weight: 'Regular (400)',
        letterSpacing: '0.25px',
        textCase: 'Original',
        textDecoration: 'Strikethrough',
        sample: SAMPLE,
      },
      {
        name: 'Body Copy (Data & Nav)/Underline/12-SemiBold',
        className: 'mbbiz-typo-body-underline-12-semibold',
        fontSize: '12px',
        lineHeight: '16px',
        weight: 'Semibold (600)',
        letterSpacing: '0.25px',
        textCase: 'Original',
        textDecoration: 'Underline',
        sample: SAMPLE,
      },
      {
        name: 'Body Copy (Data & Nav)/Underline/12-Regular',
        className: 'mbbiz-typo-body-underline-12-regular',
        fontSize: '12px',
        lineHeight: '16px',
        weight: 'Regular (400)',
        letterSpacing: '0.25px',
        textCase: 'Original',
        textDecoration: 'Underline',
        sample: SAMPLE,
      },
    ],
  },
  {
    title: 'Caption',
    id: 'typography-font-caption',
    rows: [
      {
        name: 'Caption/Normal/10-Regular',
        className: 'mbbiz-typo-caption-normal-10-regular',
        fontSize: '10px',
        lineHeight: '12px',
        weight: 'Regular (400)',
        letterSpacing: '0.25px',
        textCase: 'Original',
        textDecoration: 'None',
        sample: SAMPLE,
      },
      {
        name: 'Caption/Uppercase/10-Regular',
        className: 'mbbiz-typo-caption-uppercase-10-regular',
        fontSize: '10px',
        lineHeight: '12px',
        weight: 'Regular (400)',
        letterSpacing: '0.25px',
        textCase: 'Uppercase',
        textDecoration: 'None',
        sample: SAMPLE,
      },
      {
        name: 'Caption/Strikethrough/10-Regular',
        className: 'mbbiz-typo-caption-strikethrough-10-regular',
        fontSize: '10px',
        lineHeight: '12px',
        weight: 'Regular (400)',
        letterSpacing: '0.25px',
        textCase: 'Original',
        textDecoration: 'Strikethrough',
        sample: SAMPLE,
      },
    ],
  },
];
